### ISSUE TITLE
"You will need to enable Home Assistant" even when the skill is already present

### ISSUE THREAD

**Issue by zsawyer** [stanford-oval/almond-server#166]
Hello, 

there is something wrong with the local Home Assistant skill. 

# Issue
Once HA and Almond are both running the skill shows up under "My Skills" correctly:
> Home Assistant Gateway at http://192.168.0.12:8123
> This is your Home Assistant Gateway.

 But Almond always complains:
> me: turn fan on
> Almond: You do not have a configured. You will need to enable Home Assistant or Home Assistant before you can use that command.

## log:
```
Received assistant command turn fan on
Confidently analyzed message into $dialogue @org.thingpedia.dialogue.transaction.execute;
@org.thingpedia.iot.switch.set_power(power=enum on);
No device of kind org.thingpedia.iot.switch available, attempting configure...
Genie says: You do not have a  configured. You will need to enable Home Assistant or Home Assistant before you can use that command.
Starting to speak...
Almond sends link: /devices/create
1 24000
353444 353400
outputstream write for You do not have a  configured. You will need to enable Home Assistant or Home Assistant before you can use that command., delay of 7362.5
Done speaking
```

Note how it doesn't seem to fill the paramter for the device "have a <SOMETHING MISSING> configure". 
Also note that it tries to use the **switch** iot instead of **fan**.

# Specs
## Devices
- Raspberry Pi 4 Model B
- Philips AC1214/10 (from 2018)

## Almond
- Almond with local npm install of https://github.com/stanford-oval/almond-server/commit/0075e21b258af6d512347890fe7e9d0fa6900765

## Home Assistant 
Version | core-2021.3.2
Installation Type | Home Assistant Container

## HACS:
Installed Version | 1.11.3

### Fan Integration:
https://github.com/ronaldt80/philips-airpurifier
as fan.philips_air_purifier

# other things I have tried
When I try to setup Home Assistant as a new skill I only get redirected to here:
https://dev.almond.stanford.edu/proxy?redirect=http%3A%2F%2Fraspberrypi%3A3000&kind=io.home-assistant

**Comment by zsawyer** [comment]
Here is another log of a more fan-unique command:
```
Received assistant command is the fan oscillating?
Confidently analyzed message into $dialogue @org.thingpedia.dialogue.transaction.execute;
@org.thingpedia.iot.switch.state();
No device of kind org.thingpedia.iot.switch available, attempting configure...
Genie says: You do not have a  configured. You will need to enable Home Assistant or Home Assistant before you can use that command.
Starting to speak...
Almond sends link: /devices/create
1 24000
353444 353400
outputstream write for You do not have a  configured. You will need to enable Home Assistant or Home Assistant before you can use that command., delay of 7362.5
Done speaking

```

**Comment by gcampax** [comment]
Hi @zsawyer, thanks for testing Almond!
I don't think we have enabled fan devices yet in the new Alpha version. Not all Home Assistant devices that were available in Almond 1.* are available in this release, because we want to make sure we have good quality on the devices we enable. You can check the list at https://dev.almond.stanford.edu/thingpedia/.

For that reason, your command is interpreted as a "switch", not a "fan". You probably don't have a "switch" yet.
Now, in theory, it should reply with a sentence of the form: "You do not have a switch configured. You will need to configure it inside your Home Assistant before you can use that command."
The fact that it doesn't is a bug.

**Comment by gcampax** [comment]
I merged and deployed https://github.com/stanford-oval/almond-cloud/pull/942 on the Thingpedia server, which should fix your issue. Can you verify that?

**Comment by zsawyer** [comment]
Here is what I get right now. I have done nothing but start up almond server and inserted the question. 

```
Confidently analyzed message into $dialogue @org.thingpedia.dialogue.transaction.execute;
@org.thingpedia.iot.switch.state();
No device of kind org.thingpedia.iot.switch available, attempting configure...
Genie says: You do not have a switch configured. You will need to configure it inside your Home Assistant before you can use that command.
Starting to speak...
1 24000
361844 361800
outputstream write for You do not have a switch configured. You will need to configure it inside your Home Assistant before you can use that command., delay of 7537.5
Done speaking
```

While this fixes the error message being strange. It doesn't really solve my issue that fans are not supported yet ;). Though it is good to know why it is. 

I think the message should give some insight into exactly this and not derail the user to try to "fix" the Home Assistant configuration. 
I would be more happy if the server would respond with "Sorry, I don't know what a fan is, yet."

Maybe even have it send a link / ask if the user meant switch.

**Comment by gcampax** [comment]
Yeah, unfortunately, it's difficult for the NLP model to know about devices that are not trained. In other words, Almond does not know what a fan is, and cannot reply with a message about fans.
I think this is the best we can do for this issue, until we include support for other devices. I'm going to close this issue for now, and thanks for testing!
